### ISSUE TITLE
rzillla/dplyr.spark.hive promotion on eRum 2016

### ISSUE THREAD

**Issue by MarcinKosinski** [rzilla/dplyr.spark.hive#12]
Have you considered attending #eRum2016 with `rzilla` project or `dplyr.spark.hive` package ? 
http://www.r-bloggers.com/european-r-users-meeting-meeting-of-r-heroes-poznan-12-14-10-2016/

**Comment by piccolbo** [comment]
Let's move this to  the forum. It makes sense but doesn't seem like a sw or documentation issue.

**Comment by piccolbo** [comment]
https://groups.google.com/forum/#!topic/rzilla/A5fhUIVjHnc
